### ISSUE TITLE
GENERAL - Digitalisierung + Farbgebung des Screen-Konzepts

### ISSUE THREAD

**Issue by Merakus12** [majortomL/WI17A-Fahrgemeinschaft#15]

**Comment by IxBetaXI** [comment]
![4a96f8ff-0897-48c8-9f69-a8ef6f8dddd3](https://user-images.githubusercontent.com/47106342/52775736-a5403700-3040-11e9-95f4-f79c78909c65.png)
![8feeea5b-77cb-42f0-abc7-eeb8810a9e04](https://user-images.githubusercontent.com/47106342/52775737-a5403700-3040-11e9-816d-0f0086a30dc3.png)
![43480df1-b91a-409c-b68e-e2501c1934b0](https://user-images.githubusercontent.com/47106342/52775738-a5d8cd80-3040-11e9-96fc-bbd36095b45b.png)
![Uploading 1AC72A75-CBD3-45A0-9ED7-5AAF7B798D89.png…]()

**Comment by IxBetaXI** [comment]
![27923d4f-1023-4c0a-aae1-627194adb011](https://user-images.githubusercontent.com/47106342/52778342-1f26ef00-3046-11e9-939f-768b6340c235.png)
![07bf65ac-9571-494b-b9ac-b2171bd1deb9](https://user-images.githubusercontent.com/47106342/52778343-1f26ef00-3046-11e9-9bf2-29958b21bc9d.png)

**Comment by IxBetaXI** [comment]
![f81e9518-774c-4734-ba93-62aba1e8fe48](https://user-images.githubusercontent.com/47106342/52780913-98751080-304b-11e9-978a-3c51ff7a2619.png)

**Comment by IxBetaXI** [comment]
![af44bd25-a60b-48cd-b50d-b7bf60a42f5b](https://user-images.githubusercontent.com/47106342/52782459-69609e00-304f-11e9-8e76-c9d0db5bb1f9.png)
