### ISSUE TITLE
BACKEND - Datenbankanbindung

### ISSUE THREAD

**Issue by majortomL** [majortomL/WI17A-Fahrgemeinschaft#2]
BACKEND - Aufbau von FireBase mit Aufbau der Konzepte und Tabellen sowie Relationen. Danach Anbindung der Datenbank an die Applikation

**Comment by majortomL** [comment]
FRONTEND - Authentifikationsmaske aufbauen mit Ziel der Authentifikation per FireBase

**Comment by majortomL** [comment]
BACKEND - Ermöglichung der Authentifikation durch FrontEnd

**Comment by majortomL** [comment]
Google Maps Anbindung

**Comment by Merakus12** [comment]
Anzeigen der Daten sowohl das Schreiben der Daten ist ohne Probleme in die RTDB von FireBase möglich.
Das Löschen innerhalb RTDB ist noch nicht funktionsfähig.

Mit der Cloud-DB Lösung ist bereits alles möglich. Diese Lösung ist allerdings um einiges umständlicher zu implementieren.

**Comment by Merakus12** [comment]
@Benjamin-Wittke  hat den Löschvorgang gefixed, damit ist die DB vollständig einsatzbereit.

**Comment by Merakus12** [comment]
Sprint Meeting 25.02.2019 :
Funktioniert.
