### ISSUE TITLE
FRONTEND - MockUps für FrontEnd-Seiten

### ISSUE THREAD

**Issue by majortomL** [majortomL/WI17A-Fahrgemeinschaft#6]
Ausarbeitung des Designs der FrontEnd-Appseiten

**Comment by majortomL** [comment]
https://material.io/tools/color/#!/?view.left=0&view.right=0&primary.color=6002ee

**Comment by Merakus12** [comment]
Sprint Meeting 25.02.2019 :
wurde in anderem Issue abgehandelt.
