### ISSUE TITLE
BACKEND - Cloud Function createRide

### ISSUE THREAD

**Issue by Benjamin-Wittke** [majortomL/WI17A-Fahrgemeinschaft#9]
Mit Firebase Cloud Functions anlegen um Fahrgemeinschaft zu erstellen

**Comment by Merakus12** [comment]
Grundsätzliche DB anbindung funktioniert, warte auf Tom mit Infos zur Map - was müssen wir wie speichern ? - (Branch : Marcel_7219)

**Comment by Merakus12** [comment]
Sprint Meeting 25.02.2019 :
wird über Backend Cloud Functions gelöst.
Grundfunktion wird in den nächsten Tagen fertiggestellt, danach Pending bis Daten von Tom geliefert werden können.

**Comment by Benjamin-Wittke** [comment]
done:
Backend function über POST aufrufbar,
Parameter werden über Body transportiert und im Backend zusammengesetzt und gespeichert
